### ISSUE TITLE
login error

### ISSUE THREAD

**Issue by Eisenh** [jychuah/particle-firebase-ui#1] opened 2017-05-18 13:22 UTC
I am getting the following error when I try to login.  It began immediately after I tried to log in by using an email address/google account.  It begins to display a blank dialog with a progress bar along the top edge, which then closes and gives the error msg.  Unfortunately, it does not allow me to do as asked (sign in again).

> Error logging in: An account already exists with the same email address but different sign-in credentials. Sign in using a provider associated with this email address.

**Comment by jychuah** [comment] 2017-05-18 14:18
This may be a Firebase configuration issue. Do you have a firebase project config that you can post to a gist? (Remove the project name and other sensitive data for security) Also, can you gist the code that is generating the error?

**Comment by Eisenh** [comment] 2017-05-19 17:30
It was.  I had a user account on the Firebase project with the same email address as my Particle login, but with a different password.  After deleting that Firebase user account, I was able to get through the login again.  The Web App created a new Firebase user account for this email address.

I see a blank page with a header along the top that has "ParticleBase Controller" on the left and a dropdown listing my devices and a logout button on the right.  However, nothing happens when I select a device from the drop-down list.

**Comment by jychuah** [comment] 2017-05-22 14:02
In https://github.com/jychuah/particle-firebase-ui/blob/master/public/js/app.js there is a function called deviceSelectCallback which logs to the console device information and user information. This is the entry point for your front end code. Does it log to the console, currently?

**Comment by Eisenh** [comment] 2017-05-29 07:36
Yes, it logs to the console and gives correct details of the device selected in the dropdown.  The body below the Nav bar is still blank.  It then give user profile info and token.
This is repeated whenever I select a device from the list.  Nothing else appears in the console.

```
Currently selected device 
Object {cellular: true, connected: true, current_build_target: "0.6.2", default_build_target: "0.6.2", id: "4300500... etc.
User profile 
Object {user: S, devices: Object, token: "e7c318cb... etc.
...

**Comment by Eisenh** [comment] 2017-05-29 08:04
Correction:
The following are logged to the consol when the page is first loaded:
```

The provided value 'ms-stream' is not a valid enum value of type XMLHttpRequestResponseType.  
 checkTypeSupport	@	particle.min.js:700
The provided value 'moz-chunked-arraybuffer' is not a valid enum value of type XMLHttpRequestResponseType.  
checkTypeSupport	@	particle.min.js:700

```
For what it is worth, I don't get this message in the console when logging into the app from Internet Explorer while using a different email address to log on.  I can't use that email address with Chrome because the app won't properly sign me out (or rather, automatically signs me in with the Google auth).

**Comment by Eisenh** [comment] 2017-05-29 17:21
Another development.  If I log out , delete the user in the firebase database, and then log in again, it, of course, requests the sign-in to particle again.  However, if I sign in with a second email address that has already been used with the app, it creates a duplicate user in firebase.

**Comment by jchuahtacc** [comment] 2017-05-29 18:50
- This project is only a stub that enables you to build your own application around persisting data on Firebase. You need to build your own client code for your project that fills the body below the nav bar with whatever persistent information you need to display for your specific application. 

- Internet Explorer, depending on the version, may not print console output due to browser compatibility issues, either with console.log (https://developer.mozilla.org/en-US/docs/Web/API/Console/log) or other XMLHttpRequest compatibility issues (https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest). Without your IE version number (or a Windows development environment) I cannot replicate your error.

- You may clear your browser's login information to clear OAuth tokens.

- By default, Firebase creates a new User ID per OAuth or user creation, regardless of the e-mail address. For example, if you login to Firebase using a Google account for one address and then login to Firebase using Facebook with the same e-mail address (or even re-create the same user in Firebase using your Google account) a new User ID in Firebase will be created. There is a new option in the Firebase control panel for requesting the same User ID. In your Firebase project console, go to Authentication -> Sign-In Method -> (Scroll down) One account per e-mail address. Please read their documentation.

- I've just re-tested the project and have verified that the project is working as intended within the project scope specified, so I am closing the issue.

**Comment by jychuah** [comment] 2017-05-29 18:51
Closing issue.

**Closed as completed by jychuah** 2017-05-29 18:51 UTC
